Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
August 10, 2023 - 00:08:02
Django version 4.2.4, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

Invalid HTTP_HOST header: '54.163.159.156:8000'. You may need to add '54.163.159.156' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.163.159.156:8000'. You may need to add '54.163.159.156' to ALLOWED_HOSTS.
Bad Request: /
[10/Aug/2023 00:10:29] "GET / HTTP/1.1" 400 63237
Invalid HTTP_HOST header: '54.163.159.156:8000'. You may need to add '54.163.159.156' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '54.163.159.156:8000'. You may need to add '54.163.159.156' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[10/Aug/2023 00:10:32] "GET /favicon.ico HTTP/1.1" 400 63210
/home/ubuntu/Projects/django-todo/todoApp/settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
todos.Todo: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the TodosConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 1 issue (0 silenced).
August 10, 2023 - 00:12:00
Django version 4.2.4, using settings 'todoApp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

[10/Aug/2023 00:12:08] "GET / HTTP/1.1" 302 0
[10/Aug/2023 00:12:08] "GET /todos HTTP/1.1" 301 0
[10/Aug/2023 00:12:09] "GET /todos/ HTTP/1.1" 200 3515
[10/Aug/2023 00:12:09] "GET /static/css/style.css HTTP/1.1" 200 225
Not Found: /favicon.ico
[10/Aug/2023 00:12:11] "GET /favicon.ico HTTP/1.1" 404 2575
Not Found: /robots.txt
[10/Aug/2023 00:14:30] "GET /robots.txt HTTP/1.1" 404 2567
[10/Aug/2023 00:14:40] "GET / HTTP/1.1" 302 0
[10/Aug/2023 00:14:41] "GET /todos HTTP/1.1" 301 0
